### ISSUE TITLE
Dockerization

### ISSUE THREAD

**Issue by vanutp** [tm-a-t/TGPy#20]
Write a Dockerfile and publish to Docker Hub

**Comment by Damola12345** [comment]
hi @vanutp can i work on this task?

**Comment by vanutp** [comment]
> hi @vanutp can i work on this task?

It's already done by f8cb28dd54722c047934e41071cc32ddc6f81cdd in dev branch. The only remaining thing is CI config for automated builds. Sorry for bad issue management.

**Comment by vanutp** [comment]
fixed in f8cb28dd54722c047934e41071cc32ddc6f81cdd
