### ISSUE TITLE
First reaction triggers running the code

### ISSUE THREAD

**Issue by tm-a-t** [tm-a-t/TGPy#25]
Once a code snippet message gets a first reaction, TGPy treats the message as edited and reruns the code. Telegram bug?

**Comment by ntoneee** [comment]
Telegram client getting an update looking like the message text was edited is not a documented feature of Telegram. According to the article https://core.telegram.org/api/reactions Telegram should send an updateMessageReactions instead of updateEditMessage

**Comment by vanutp** [comment]
fixed in cf6e64e
