### ISSUE TITLE
Rewrite in rust

### ISSUE THREAD

**Issue by WeetHet** [tm-a-t/TGPy#34]
Rust is a memory-safe and secure language and is more efficient than Python. It is type safe and has better telegram support. Also, the industry trend is shifting towards Rust so we should rewrite this in Rust.

**Comment by vanutp** [comment]
Go ahead, as I said 1874 times

**Comment by WeetHet** [comment]
Leave the issue open then

**Comment by vanutp** [comment]
> Leave the issue open then

TGPy stands for TeleGram Python
